name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Node dependencies
        run: npm ci

      - name: Build static site
        env:
          NEXT_BASE_PATH: /${{ github.event.repository.name }}
          NEXT_ASSET_PREFIX: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
        run: npm run build

      - name: Add .nojekyll
        run: mkdir -p out && touch out/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Node dependencies
        run: npm ci

      - name: Run unit tests (Vitest)
        if: ${{ hashFiles('tests/**/*') != '' }}
        run: npm run test -- tests

      - name: No tests found, skipping
        if: ${{ hashFiles('tests/**/*') == '' }}
        run: echo "No tests found in tests/, skipping test run."

  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
